<#
  PolarHQ — self-host installer for Windows (PowerShell 5.1+ / 7+).

    irm https://dl.polarhq.app/install.ps1 | iex

  Non-interactive (headless) install:
    $env:POLARHQ_DOMAIN="cloud.example.com"; $env:POLARHQ_EMAIL="you@example.com"
    irm https://dl.polarhq.app/install.ps1 | iex

  Environment overrides:
    POLARHQ_DIR     install directory        (default: %USERPROFILE%\polarhq)
    POLARHQ_DOMAIN  domain for auto-HTTPS    (blank = local https://localhost, self-signed)
    POLARHQ_EMAIL   Let's Encrypt contact    (optional)
#>
$ErrorActionPreference = 'Stop'

$AppName    = 'PolarHQ'
$AppImage   = 'ghcr.io/marquescoding/polarhq-app:latest'
$WebImage   = 'ghcr.io/marquescoding/polarhq-web:latest'
$InstallDir = if ($env:POLARHQ_DIR) { $env:POLARHQ_DIR } else { Join-Path $env:USERPROFILE 'polarhq' }

function Info($m) { Write-Host "-> $m" -ForegroundColor Cyan }
function Ok($m)   { Write-Host "OK $m" -ForegroundColor Green }
function Warn($m) { Write-Host "!  $m" -ForegroundColor Yellow }
function Die($m)  { Write-Host "x  $m" -ForegroundColor Red; exit 1 }

function New-Bytes([int]$n) {
  $b = New-Object 'byte[]' $n
  ([System.Security.Cryptography.RandomNumberGenerator]::Create()).GetBytes($b)
  , $b
}
function New-B64([int]$n = 32) { [Convert]::ToBase64String((New-Bytes $n)) }
function New-Alnum([int]$len = 32) {
  $c = [char[]]'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'
  -join ((New-Bytes $len) | ForEach-Object { $c[$_ % $c.Length] })
}

Write-Host ""
Write-Host "  PolarHQ" -ForegroundColor White -NoNewline; Write-Host " - self-host installer" -ForegroundColor DarkGray
Write-Host "  Photos, Drive, Docs, Sheets - end-to-end encrypted, on your own server." -ForegroundColor DarkGray
Write-Host ""

# ---------------------------------------------------------------- prerequisites
if (-not (Get-Command docker -ErrorAction SilentlyContinue)) {
  Die "Docker Desktop is not installed. Install it, start it, then re-run: https://docs.docker.com/desktop/install/windows-install/"
}
docker info *> $null
if ($LASTEXITCODE -ne 0) {
  Die "Docker is installed but not running. Start Docker Desktop and wait for it to finish, then re-run."
}
Ok "Docker is running"

docker compose version *> $null
if ($LASTEXITCODE -eq 0) {
  $UseV2 = $true
} elseif (Get-Command docker-compose -ErrorAction SilentlyContinue) {
  $UseV2 = $false
} else {
  Die "Docker Compose v2 not found. Update Docker Desktop (Compose is bundled)."
}
function Compose { if ($UseV2) { & docker compose @args } else { & docker-compose @args } }
Ok "Compose available"

# ---------------------------------------------------------------- configuration
$domain = $env:POLARHQ_DOMAIN
$email  = $env:POLARHQ_EMAIL
if (-not $domain) {
  Write-Host ""
  Write-Host "Where will $AppName run?" -ForegroundColor White
  Write-Host "  - Enter a domain you control (its DNS already points here) for automatic HTTPS."
  Write-Host "  - Leave blank to run locally on https://localhost with a self-signed certificate."
  $domain = Read-Host "Domain"
}

if ($domain -and $domain -ne 'localhost') {
  $mode = 'domain'; $publicUrl = "https://$domain"
  if (-not $email) { $email = Read-Host "Email for Let's Encrypt renewals (optional)" }
} else {
  $mode = 'local'; $domain = 'localhost'; $publicUrl = 'https://localhost'
}

New-Item -ItemType Directory -Force -Path $InstallDir | Out-Null
Set-Location $InstallDir
$envPath   = Join-Path $InstallDir '.env'
$caddyPath = Join-Path $InstallDir 'Caddyfile'
$compPath  = Join-Path $InstallDir 'docker-compose.yml'

# Preserve existing secrets on re-run — rotating AUTH_SECRET would orphan encrypted
# data and changing the DB password would lock the app out of Postgres.
$authSecret = $null; $pgPass = $null
if (Test-Path $envPath) {
  Get-Content $envPath | ForEach-Object {
    if ($_ -match '^AUTH_SECRET=(.*)$')       { $authSecret = $Matches[1] }
    elseif ($_ -match '^POSTGRES_PASSWORD=(.*)$') { $pgPass = $Matches[1] }
  }
}
if (-not $authSecret) { $authSecret = New-B64 }
if (-not $pgPass)     { $pgPass = New-Alnum }

# ---------------------------------------------------------------- .env (secrets)
$envContent = @"
# Generated by the PolarHQ installer - keep this file private (it holds your secrets).
APP_NAME=$AppName
PUBLIC_URL=$publicUrl
DOMAIN=$domain
AUTH_SECRET=$authSecret
POSTGRES_PASSWORD=$pgPass
APP_IMAGE=$AppImage
WEB_IMAGE=$WebImage
"@
[System.IO.File]::WriteAllText($envPath, $envContent)
Ok "Wrote .env"

# ---------------------------------------------------------------- Caddyfile (TLS)
if ($mode -eq 'domain') {
  $emailBlock = if ($email) { "{`n`temail $email`n}`n`n" } else { "" }
  $caddy = @"
$emailBlock$domain {
	encode zstd gzip
	@api path /api/* /ws /ws/* /health /_sodium.js /s/*
	handle @api {
		reverse_proxy api:3001
	}
	handle {
		reverse_proxy web:3000
	}
}
"@
} else {
  $caddy = @"
{
	auto_https disable_redirects
}

https://localhost {
	tls internal
	encode zstd gzip
	@api path /api/* /ws /ws/* /health /_sodium.js /s/*
	handle @api {
		reverse_proxy api:3001
	}
	handle {
		reverse_proxy web:3000
	}
}
"@
}
[System.IO.File]::WriteAllText($caddyPath, $caddy)
Ok "Wrote Caddyfile ($mode TLS)"

# ---------------------------------------------------------------- docker-compose
$compose = @'
name: polarhq

x-app-env: &app-env
  NODE_ENV: production
  APP_NAME: ${APP_NAME:-PolarHQ}
  AUTH_SECRET: ${AUTH_SECRET}
  API_URL: ${PUBLIC_URL}
  WEB_URL: ${PUBLIC_URL}
  DATABASE_URL: postgres://orbit:${POSTGRES_PASSWORD}@postgres:5432/orbit
  REDIS_URL: redis://redis:6379
  STORAGE_DRIVER: fs
  STORAGE_FS_ROOT: /data/storage

services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: orbit
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: orbit
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U orbit -d orbit"]
      interval: 5s
      timeout: 5s
      retries: 20

  redis:
    image: redis:8-alpine
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis-data:/data

  migrate:
    image: ${APP_IMAGE}
    environment: *app-env
    command: ["pnpm", "--filter", "@workspace/db", "db:migrate"]
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

  api:
    image: ${APP_IMAGE}
    restart: unless-stopped
    environment: *app-env
    volumes:
      - storage-data:/data/storage
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  media:
    image: ${APP_IMAGE}
    restart: unless-stopped
    environment: *app-env
    command: ["pnpm", "--filter", "@workspace/media", "start"]
    volumes:
      - storage-data:/data/storage
    depends_on:
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  backup:
    image: ${APP_IMAGE}
    restart: unless-stopped
    environment: *app-env
    command: ["pnpm", "--filter", "@workspace/backup", "start"]
    volumes:
      - storage-data:/data/storage
    depends_on:
      redis:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  web:
    image: ${WEB_IMAGE}
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PUBLIC_URL: ${PUBLIC_URL}
    depends_on:
      - api

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - web
      - api

volumes:
  postgres-data:
  redis-data:
  storage-data:
  caddy-data:
  caddy-config:
'@
[System.IO.File]::WriteAllText($compPath, $compose)
Ok "Wrote docker-compose.yml"

# ---------------------------------------------------------------- launch
Write-Host ""
Info "Pulling images - first run downloads a few hundred MB, please wait..."
Compose pull
if ($LASTEXITCODE -ne 0) { Die "docker compose pull failed." }
Write-Host ""
Info "Starting $AppName..."
Compose up -d
if ($LASTEXITCODE -ne 0) { Die "docker compose up failed." }

# ---------------------------------------------------------------- done
Write-Host ""
Ok "$AppName is up."
Write-Host ""
Write-Host "  Open     $publicUrl" -ForegroundColor Cyan
Write-Host "  Folder   $InstallDir"
Write-Host "  Logs     cd `"$InstallDir`"; docker compose logs -f"
Write-Host "  Stop     cd `"$InstallDir`"; docker compose down"
Write-Host "  Update   cd `"$InstallDir`"; docker compose pull; docker compose up -d"
Write-Host ""
if ($mode -eq 'local') {
  Warn "Local mode uses a self-signed certificate - your browser will warn once; accept it to continue."
} else {
  Info "Ensure $domain resolves to this machine and ports 80/443 are open - Caddy fetches a certificate automatically (can take ~30s on first load)."
}
Write-Host ""
