/** Short descriptions for common spreadsheet functions, shown in autocomplete. */
export const FUNCTION_DOCS: Record<string, string> = {
  SUM: "Sum of a series of numbers and/or cells.",
  AVERAGE: "The numerical average of a dataset, ignoring text.",
  COUNT: "Count of numeric values in a dataset.",
  COUNTA: "Count of values, including text, in a dataset.",
  COUNTIF: "Count of cells in a range meeting a condition.",
  SUMIF: "A conditional sum across a range.",
  SUMIFS: "Sum of a range depending on multiple criteria.",
  IF: "Returns one value if a condition is true, another if false.",
  IFERROR: "Returns a value if no error, otherwise a fallback.",
  MIN: "The minimum value in a dataset.",
  MAX: "The maximum value in a dataset.",
  ROUND: "Rounds a number to a given number of decimal places.",
  ROUNDUP: "Rounds a number up to a number of decimal places.",
  ROUNDDOWN: "Rounds a number down to a number of decimal places.",
  ABS: "The absolute value of a number.",
  SQRT: "The positive square root of a number.",
  POWER: "A number raised to a power.",
  MOD: "The remainder after division.",
  PRODUCT: "The product of a series of numbers.",
  MEDIAN: "The median value in a dataset.",
  VLOOKUP: "Searches down the first column of a range for a key.",
  HLOOKUP: "Searches across the first row of a range for a key.",
  INDEX: "The content of a cell at a given row/column offset.",
  MATCH: "The relative position of an item in a range.",
  CONCATENATE: "Appends strings to one another.",
  CONCAT: "Appends strings to one another.",
  LEFT: "A substring from the start of a string.",
  RIGHT: "A substring from the end of a string.",
  MID: "A substring from the middle of a string.",
  LEN: "The length of a string.",
  UPPER: "Converts a string to uppercase.",
  LOWER: "Converts a string to lowercase.",
  TRIM: "Removes leading and trailing spaces.",
  TODAY: "The current date.",
  NOW: "The current date and time.",
  DATE: "Builds a date from year, month and day.",
  AND: "True if all arguments are true.",
  OR: "True if any argument is true.",
  NOT: "Reverses a logical value.",
}
