import Foundation
import Testing
@testable import OrbitCrypto

/// Validates that `OrbitCrypto` reproduces the web suite's JS crypto byte-for-byte,
/// using vectors generated by `apps/web/scripts/gen-crypto-vectors.ts`.
struct OrbitCryptoTests {
    static let vectors: Vectors = {
        let url = Bundle.module.url(forResource: "vectors", withExtension: "json")!
        let data = try! Data(contentsOf: url)
        return try! JSONDecoder().decode(Vectors.self, from: data)
    }()

    @Test func derivesKeyForEachParamSet() throws {
        for v in Self.vectors.deriveKey {
            let key = try OrbitCrypto.deriveKey(
                password: v.password,
                salt: try OrbitCrypto.fromBase64(v.salt),
                ops: v.ops,
                mem: v.mem
            )
            #expect(OrbitCrypto.toBase64(key) == v.expected)
        }
    }

    @Test func opensSecretbox() throws {
        let v = Self.vectors.secretboxOpen
        let plain = try OrbitCrypto.secretboxOpen(try OrbitCrypto.fromBase64(v.blob), key: try OrbitCrypto.fromBase64(v.key))
        #expect(OrbitCrypto.toBase64(plain) == v.expected)
    }

    @Test func opensSealedBox() throws {
        let v = Self.vectors.sealedBoxOpen
        let pair = OrbitCrypto.Keypair(
            publicKey: try OrbitCrypto.fromBase64(v.publicKey),
            privateKey: try OrbitCrypto.fromBase64(v.privateKey)
        )
        let plain = try OrbitCrypto.sealedBoxOpen(try OrbitCrypto.fromBase64(v.sealed), keypair: pair)
        #expect(OrbitCrypto.toBase64(plain) == v.expected)
    }

    @Test func roundTripsSecretbox() throws {
        let key = try OrbitCrypto.fromBase64(Self.vectors.secretboxOpen.key)
        let message = Data("orbit round trip ✅".utf8)
        let sealed = try OrbitCrypto.secretboxSeal(message, key: key)
        #expect(try OrbitCrypto.secretboxOpen(sealed, key: key) == message)
    }

    /// The real unlock path: password → private key → meta key → content key → thumbnail bytes.
    @Test func reproducesFullUnlockChain() throws {
        let v = Self.vectors.unlockChain
        let kek = try OrbitCrypto.deriveKey(
            password: v.password,
            salt: try OrbitCrypto.fromBase64(v.salt),
            ops: v.ops,
            mem: v.mem
        )
        let privateKey = try OrbitCrypto.secretboxOpen(try OrbitCrypto.fromBase64(v.wrappedPrivateKey), key: kek)
        #expect(OrbitCrypto.toBase64(privateKey) == v.expectedPrivateKey)

        let pair = OrbitCrypto.Keypair(
            publicKey: try OrbitCrypto.fromBase64(v.publicKey),
            privateKey: privateKey
        )
        let metaKey = try OrbitCrypto.sealedBoxOpen(try OrbitCrypto.fromBase64(v.wrappedMetaKey), keypair: pair)
        #expect(OrbitCrypto.toBase64(metaKey) == v.expectedMetaKey)

        let contentKey = try OrbitCrypto.sealedBoxOpen(try OrbitCrypto.fromBase64(v.wrappedContentKey), keypair: pair)
        let thumb = try OrbitCrypto.secretboxOpen(try OrbitCrypto.fromBase64(v.thumbBlob), key: contentKey)
        #expect(OrbitCrypto.toBase64(thumb) == v.expectedThumb)
    }
}

struct Vectors: Decodable {
    struct Derive: Decodable {
        let password: String
        let salt: String
        let ops: Int
        let mem: Int
        let expected: String
    }
    struct SecretboxOpen: Decodable { let key: String; let blob: String; let expected: String }
    struct SealedBoxOpen: Decodable {
        let publicKey: String
        let privateKey: String
        let sealed: String
        let expected: String
    }
    struct UnlockChain: Decodable {
        let password: String
        let salt: String
        let ops: Int
        let mem: Int
        let publicKey: String
        let wrappedPrivateKey: String
        let expectedPrivateKey: String
        let wrappedMetaKey: String
        let expectedMetaKey: String
        let wrappedContentKey: String
        let thumbBlob: String
        let expectedThumb: String
    }

    let deriveKey: [Derive]
    let secretboxOpen: SecretboxOpen
    let sealedBoxOpen: SealedBoxOpen
    let unlockChain: UnlockChain
}
