import Foundation
import XCTest
@testable import OrbitCrypto

/// Validates that `OrbitCrypto` reproduces the web suite's JS crypto byte-for-byte,
/// using vectors generated by `apps/web/scripts/gen-crypto-vectors.ts`.
final class OrbitCryptoTests: XCTestCase {
    private lazy var vectors: Vectors = {
        let url = Bundle.module.url(forResource: "vectors", withExtension: "json")!
        let data = try! Data(contentsOf: url)
        return try! JSONDecoder().decode(Vectors.self, from: data)
    }()

    func testDerivesKeyForEachParamSet() throws {
        for v in vectors.deriveKey {
            let key = try OrbitCrypto.deriveKey(
                password: v.password,
                salt: try OrbitCrypto.fromBase64(v.salt),
                ops: v.ops,
                mem: v.mem
            )
            XCTAssertEqual(OrbitCrypto.toBase64(key), v.expected)
        }
    }

    func testOpensSecretbox() throws {
        let v = vectors.secretboxOpen
        let plain = try OrbitCrypto.secretboxOpen(
            try OrbitCrypto.fromBase64(v.blob),
            key: try OrbitCrypto.fromBase64(v.key)
        )
        XCTAssertEqual(OrbitCrypto.toBase64(plain), v.expected)
    }

    func testOpensSealedBox() throws {
        let v = vectors.sealedBoxOpen
        let pair = OrbitCrypto.Keypair(
            publicKey: try OrbitCrypto.fromBase64(v.publicKey),
            privateKey: try OrbitCrypto.fromBase64(v.privateKey)
        )
        let plain = try OrbitCrypto.sealedBoxOpen(try OrbitCrypto.fromBase64(v.sealed), keypair: pair)
        XCTAssertEqual(OrbitCrypto.toBase64(plain), v.expected)
    }

    func testRoundTripsSecretbox() throws {
        let key = try OrbitCrypto.fromBase64(vectors.secretboxOpen.key)
        let message = Data("orbit round trip ✅".utf8)
        let sealed = try OrbitCrypto.secretboxSeal(message, key: key)
        XCTAssertEqual(try OrbitCrypto.secretboxOpen(sealed, key: key), message)
    }

    /// The real unlock path: password → private key → meta key → content key → thumbnail bytes.
    func testReproducesFullUnlockChain() throws {
        let v = vectors.unlockChain
        let kek = try OrbitCrypto.deriveKey(
            password: v.password,
            salt: try OrbitCrypto.fromBase64(v.salt),
            ops: v.ops,
            mem: v.mem
        )
        let privateKey = try OrbitCrypto.secretboxOpen(try OrbitCrypto.fromBase64(v.wrappedPrivateKey), key: kek)
        XCTAssertEqual(OrbitCrypto.toBase64(privateKey), v.expectedPrivateKey)

        let pair = OrbitCrypto.Keypair(
            publicKey: try OrbitCrypto.fromBase64(v.publicKey),
            privateKey: privateKey
        )
        let metaKey = try OrbitCrypto.sealedBoxOpen(try OrbitCrypto.fromBase64(v.wrappedMetaKey), keypair: pair)
        XCTAssertEqual(OrbitCrypto.toBase64(metaKey), v.expectedMetaKey)

        let contentKey = try OrbitCrypto.sealedBoxOpen(try OrbitCrypto.fromBase64(v.wrappedContentKey), keypair: pair)
        let thumb = try OrbitCrypto.secretboxOpen(try OrbitCrypto.fromBase64(v.thumbBlob), key: contentKey)
        XCTAssertEqual(OrbitCrypto.toBase64(thumb), v.expectedThumb)
    }
}

struct Vectors: Decodable {
    struct Derive: Decodable {
        let password: String
        let salt: String
        let ops: Int
        let mem: Int
        let expected: String
    }
    struct SecretboxOpen: Decodable { let key: String; let blob: String; let expected: String }
    struct SealedBoxOpen: Decodable {
        let publicKey: String
        let privateKey: String
        let sealed: String
        let expected: String
    }
    struct UnlockChain: Decodable {
        let password: String
        let salt: String
        let ops: Int
        let mem: Int
        let publicKey: String
        let wrappedPrivateKey: String
        let expectedPrivateKey: String
        let wrappedMetaKey: String
        let expectedMetaKey: String
        let wrappedContentKey: String
        let thumbBlob: String
        let expectedThumb: String
    }

    let deriveKey: [Derive]
    let secretboxOpen: SecretboxOpen
    let sealedBoxOpen: SealedBoxOpen
    let unlockChain: UnlockChain
}
